{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/continueFlow(from:)"},"kind":"symbol","abstract":[{"text":"Continues Link from an OAuth redirectUri received from an out-of-process OAuth flow (","type":"text"},{"type":"emphasis","inlineContent":[{"text":"e.g.","type":"text"}]},{"type":"text","text":", an institution’s app)."}],"variants":[{"paths":["\/documentation\/moneykit\/mklinkhandler\/continueflow(from:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.moneykit.link\/documentation\/MoneyKit","doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler"]]},"metadata":{"modules":[{"name":"MoneyKit"}],"symbolKind":"method","title":"continueFlow(from:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"continueFlow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","externalID":"s:8MoneyKit13MKLinkHandlerC12continueFlow4fromy10Foundation3URLV_tF"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"continueFlow","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"text":" ","kind":"text"},{"text":"redirectUri","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The uri from which the flow was redirected."}],"type":"paragraph"}],"name":"redirectUri"}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"If the "},{"type":"codeVoice","code":"redirectUri"},{"type":"text","text":" parameter is not expected an error will be thrown to the "},{"type":"codeVoice","code":"MKConfiguration"},{"type":"text","text":" error handler."}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler/continueFlow(from:)":{"role":"symbol","abstract":[{"type":"text","text":"Continues Link from an OAuth redirectUri received from an out-of-process OAuth flow ("},{"type":"emphasis","inlineContent":[{"text":"e.g.","type":"text"}]},{"text":", an institution’s app).","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueFlow"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}],"url":"\/documentation\/moneykit\/mklinkhandler\/continueflow(from:)","type":"topic","kind":"symbol","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/continueFlow(from:)","title":"continueFlow(from:)"},"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler":{"type":"topic","title":"MKLinkHandler","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MKLinkHandler","kind":"identifier"}],"identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler","abstract":[{"code":"MKLinkHandler","type":"codeVoice"},{"type":"text","text":" provides ways to open the MoneyKit SDK."}],"kind":"symbol","url":"\/documentation\/moneykit\/mklinkhandler","navigatorTitle":[{"kind":"identifier","text":"MKLinkHandler"}]},"doc://com.moneykit.link/documentation/MoneyKit":{"url":"\/documentation\/moneykit","kind":"symbol","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit","type":"topic","abstract":[{"text":"Internet Money Magic","type":"text"}],"title":"MoneyKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/title","value":"MKLinkHandler"},{"value":[{"kind":"identifier","text":"MKLinkHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/fragments"},{"value":[{"kind":"identifier","text":"MKLinkHandler"}],"path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}