{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.moneykit.link\/documentation\/MoneyKit","doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:8MoneyKit15MKConfigurationV","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKConfiguration","kind":"typeIdentifier","text":"MKConfiguration"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The configuration used to customize and receive callbacks from the link handler.","type":"text"}]}],"name":"configuration"}],"kind":"parameters"}],"metadata":{"modules":[{"name":"MoneyKit"}],"roleHeading":"Initializer","role":"symbol","externalID":"s:8MoneyKit13MKLinkHandlerC13configurationAcA15MKConfigurationV_tcfc","title":"init(configuration:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MKConfiguration","preciseIdentifier":"s:8MoneyKit15MKConfigurationV"},{"kind":"text","text":")"}],"symbolKind":"init"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/moneykit\/mklinkhandler\/init(configuration:)"]}],"abstract":[{"type":"text","text":"Initializes and returns a newly created link handler with the provided configuration."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/init(configuration:)","interfaceLanguage":"swift"},"references":{"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler":{"abstract":[{"type":"codeVoice","code":"MKLinkHandler"},{"type":"text","text":" provides ways to open the MoneyKit SDK."}],"url":"\/documentation\/moneykit\/mklinkhandler","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKLinkHandler","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MKLinkHandler","kind":"identifier"}],"title":"MKLinkHandler"},"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler/init(configuration:)":{"type":"topic","abstract":[{"type":"text","text":"Initializes and returns a newly created link handler with the provided configuration."}],"url":"\/documentation\/moneykit\/mklinkhandler\/init(configuration:)","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/init(configuration:)","title":"init(configuration:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MKConfiguration","kind":"typeIdentifier","preciseIdentifier":"s:8MoneyKit15MKConfigurationV"},{"kind":"text","text":")"}]},"doc://com.moneykit.link/documentation/MoneyKit":{"url":"\/documentation\/moneykit","kind":"symbol","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit","abstract":[{"text":"Internet Money Magic","type":"text"}],"role":"collection","type":"topic","title":"MoneyKit"},"doc://com.moneykit.link/documentation/MoneyKit/MKConfiguration":{"role":"symbol","title":"MKConfiguration","abstract":[{"type":"codeVoice","code":"MKConfiguration"},{"type":"text","text":" is the main entrypoint for the MoneyKit SDK."}],"navigatorTitle":[{"kind":"identifier","text":"MKConfiguration"}],"type":"topic","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKConfiguration","url":"\/documentation\/moneykit\/mkconfiguration","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MKConfiguration"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/title","value":"MKLinkHandler"},{"value":[{"kind":"identifier","text":"MKLinkHandler"}],"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/navigatorTitle","value":[{"text":"MKLinkHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}