{"hierarchy":{"paths":[["doc:\/\/com.moneykit.link\/documentation\/MoneyKit","doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/presentLinkFlow(on:)"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"MoneyKit"}],"title":"presentLinkFlow(on:)","externalID":"s:8MoneyKit13MKLinkHandlerC15presentLinkFlow2onySo16UIViewControllerC_tF","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentLinkFlow"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":")","kind":"text"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentLinkFlow"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"presentingViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"presentingViewController","content":[{"inlineContent":[{"type":"text","text":"The view controller on which to present the link flow."}],"type":"paragraph"}]}]}],"abstract":[{"text":"Calling ","type":"text"},{"code":"presentLinkFlow","type":"codeVoice"},{"text":" will present the link flow to your user.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Once "},{"type":"codeVoice","code":"presentLinkFlow"},{"type":"text","text":" is called, you will begin receiving events via the onEvent callback."}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/moneykit\/mklinkhandler\/presentlinkflow(on:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler":{"abstract":[{"code":"MKLinkHandler","type":"codeVoice"},{"type":"text","text":" provides ways to open the MoneyKit SDK."}],"title":"MKLinkHandler","kind":"symbol","url":"\/documentation\/moneykit\/mklinkhandler","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MKLinkHandler"}],"identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler","role":"symbol","navigatorTitle":[{"text":"MKLinkHandler","kind":"identifier"}]},"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler/presentLinkFlow(on:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentLinkFlow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":")","kind":"text"}],"kind":"symbol","title":"presentLinkFlow(on:)","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/presentLinkFlow(on:)","type":"topic","role":"symbol","abstract":[{"text":"Calling ","type":"text"},{"code":"presentLinkFlow","type":"codeVoice"},{"type":"text","text":" will present the link flow to your user."},{"text":" ","type":"text"},{"type":"text","text":"Once "},{"type":"codeVoice","code":"presentLinkFlow"},{"text":" is called, you will begin receiving events via the onEvent callback.","type":"text"}],"url":"\/documentation\/moneykit\/mklinkhandler\/presentlinkflow(on:)"},"doc://com.moneykit.link/documentation/MoneyKit":{"kind":"symbol","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit","role":"collection","url":"\/documentation\/moneykit","title":"MoneyKit","type":"topic","abstract":[{"text":"Internet Money Magic","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MKLinkHandler","op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MKLinkHandler"}],"path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/fragments"},{"path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MKLinkHandler"}]}]}]}