{"abstract":[{"code":"MKLinkHandler","type":"codeVoice"},{"text":" provides ways to open the MoneyKit SDK.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.moneykit.link\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.moneykit.link\/objc(pl)NSObject","doc:\/\/com.moneykit.link\/s7CVarArgP","doc:\/\/com.moneykit.link\/s28CustomDebugStringConvertibleP","doc:\/\/com.moneykit.link\/s23CustomStringConvertibleP","doc:\/\/com.moneykit.link\/SQ","doc:\/\/com.moneykit.link\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MKLinkHandler"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler"},"metadata":{"roleHeading":"Class","title":"MKLinkHandler","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MKLinkHandler","kind":"identifier"}],"modules":[{"name":"MoneyKit"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@MoneyKit@objc(cs)MKLinkHandler","navigatorTitle":[{"text":"MKLinkHandler","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.moneykit.link\/documentation\/MoneyKit"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/moneykit\/mklinkhandler"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/moneykit\/mklinkhandler"]}],"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/init(configuration:)"]},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/continueFlow(from:)","doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/presentLinkFlow(on:)"],"title":"Instance Methods"}],"references":{"doc://com.moneykit.link/s7CVarArgP":{"identifier":"doc:\/\/com.moneykit.link\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.moneykit.link/objc(pl)NSObject":{"identifier":"doc:\/\/com.moneykit.link\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.moneykit.link/SQ":{"identifier":"doc:\/\/com.moneykit.link\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.moneykit.link/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.moneykit.link\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler/presentLinkFlow(on:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentLinkFlow"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Calling "},{"code":"presentLinkFlow","type":"codeVoice"},{"type":"text","text":" will present the link flow to your user."},{"text":" ","type":"text"},{"text":"Once ","type":"text"},{"code":"presentLinkFlow","type":"codeVoice"},{"text":" is called, you will begin receiving events via the onEvent callback.","type":"text"}],"title":"presentLinkFlow(on:)","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/presentLinkFlow(on:)","url":"\/documentation\/moneykit\/mklinkhandler\/presentlinkflow(on:)","role":"symbol"},"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler/init(configuration:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:8MoneyKit15MKConfigurationV","kind":"typeIdentifier","text":"MKConfiguration"},{"kind":"text","text":")"}],"title":"init(configuration:)","role":"symbol","kind":"symbol","url":"\/documentation\/moneykit\/mklinkhandler\/init(configuration:)","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/init(configuration:)","type":"topic","abstract":[{"text":"Initializes and returns a newly created link handler with the provided configuration.","type":"text"}]},"doc://com.moneykit.link/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.moneykit.link\/objc(cs)NSObject","title":"NSObject"},"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler/continueFlow(from:)":{"identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler\/continueFlow(from:)","kind":"symbol","title":"continueFlow(from:)","type":"topic","abstract":[{"type":"text","text":"Continues Link from an OAuth redirectUri received from an out-of-process OAuth flow ("},{"inlineContent":[{"type":"text","text":"e.g."}],"type":"emphasis"},{"text":", an institution’s app).","type":"text"}],"url":"\/documentation\/moneykit\/mklinkhandler\/continueflow(from:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"continueFlow"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.moneykit.link/SH":{"type":"unresolvable","identifier":"doc:\/\/com.moneykit.link\/SH","title":"Swift.Hashable"},"doc://com.moneykit.link/documentation/MoneyKit":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit","url":"\/documentation\/moneykit","abstract":[{"type":"text","text":"Internet Money Magic"}],"title":"MoneyKit","role":"collection"},"doc://com.moneykit.link/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.moneykit.link\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler":{"identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MKLinkHandler","kind":"identifier"}],"title":"MKLinkHandler","navigatorTitle":[{"kind":"identifier","text":"MKLinkHandler"}],"kind":"symbol","url":"\/documentation\/moneykit\/mklinkhandler","type":"topic","abstract":[{"type":"codeVoice","code":"MKLinkHandler"},{"text":" provides ways to open the MoneyKit SDK.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"MKLinkHandler"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"MKLinkHandler"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"MKLinkHandler","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":null},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.moneykit.link\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MKLinkHandler","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/title","value":"MKLinkHandler"},{"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/fragments","value":[{"text":"MKLinkHandler","kind":"identifier"}]},{"value":[{"text":"MKLinkHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/navigatorTitle"}]}]}