{"hierarchy":{"paths":[["doc:\/\/com.moneykit.link\/documentation\/MoneyKit","doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKConnectViewModel"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"linkHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MKLinkHandler","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler","preciseIdentifier":"c:@M@MoneyKit@objc(cs)MKLinkHandler","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"linkHandler"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MKLinkHandler","preciseIdentifier":"c:@M@MoneyKit@objc(cs)MKLinkHandler"},{"text":"?)","kind":"text"}],"modules":[{"name":"MoneyKit"}],"externalID":"s:8MoneyKit18MKConnectViewModelC11linkHandlerAcA06MKLinkG0CSg_tcfc","title":"init(linkHandler:)","roleHeading":"Initializer","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/moneykit\/mkconnectviewmodel\/init(linkhandler:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKConnectViewModel\/init(linkHandler:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://com.moneykit.link/documentation/MoneyKit":{"type":"topic","role":"collection","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit","kind":"symbol","title":"MoneyKit","url":"\/documentation\/moneykit","abstract":[{"type":"text","text":"Internet Money Magic"}]},"doc://com.moneykit.link/documentation/MoneyKit/MKConnectViewModel/init(linkHandler:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKConnectViewModel\/init(linkHandler:)","abstract":[],"url":"\/documentation\/moneykit\/mkconnectviewmodel\/init(linkhandler:)","title":"init(linkHandler:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"linkHandler"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MKLinkHandler","preciseIdentifier":"c:@M@MoneyKit@objc(cs)MKLinkHandler"},{"text":"?)","kind":"text"}]},"doc://com.moneykit.link/documentation/MoneyKit/MKConnectViewModel":{"url":"\/documentation\/moneykit\/mkconnectviewmodel","kind":"symbol","title":"MKConnectViewModel","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKConnectViewModel","kind":"identifier"}],"navigatorTitle":[{"text":"MKConnectViewModel","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKConnectViewModel"},"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler":{"identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler","title":"MKLinkHandler","kind":"symbol","type":"topic","abstract":[{"type":"codeVoice","code":"MKLinkHandler"},{"type":"text","text":" provides ways to open the MoneyKit SDK."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKLinkHandler","kind":"identifier"}],"role":"symbol","url":"\/documentation\/moneykit\/mklinkhandler","navigatorTitle":[{"kind":"identifier","text":"MKLinkHandler"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/title","value":"MKLinkHandler"},{"value":[{"text":"MKLinkHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/fragments"},{"path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/navigatorTitle","value":[{"text":"MKLinkHandler","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}