{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"linkHandler","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"linkHandler"},{"text":": ","kind":"text"},{"text":"MKLinkHandler","kind":"typeIdentifier","preciseIdentifier":"c:@M@MoneyKit@objc(cs)MKLinkHandler"},{"text":"?","kind":"text"}],"modules":[{"name":"MoneyKit"}],"role":"symbol","symbolKind":"property","externalID":"s:8MoneyKit18MKConnectViewModelC11linkHandlerAA06MKLinkG0CSgvp","roleHeading":"Instance Property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/moneykit\/mkconnectviewmodel\/linkhandler"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"linkHandler"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MoneyKit@objc(cs)MKLinkHandler","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler","text":"MKLinkHandler"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKConnectViewModel\/linkHandler"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.moneykit.link\/documentation\/MoneyKit","doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKConnectViewModel"]]},"references":{"doc://com.moneykit.link/documentation/MoneyKit/MKLinkHandler":{"role":"symbol","url":"\/documentation\/moneykit\/mklinkhandler","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKLinkHandler"}],"navigatorTitle":[{"kind":"identifier","text":"MKLinkHandler"}],"kind":"symbol","title":"MKLinkHandler","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKLinkHandler","abstract":[{"type":"codeVoice","code":"MKLinkHandler"},{"type":"text","text":" provides ways to open the MoneyKit SDK."}]},"doc://com.moneykit.link/documentation/MoneyKit":{"type":"topic","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit","title":"MoneyKit","kind":"symbol","url":"\/documentation\/moneykit","abstract":[{"type":"text","text":"Internet Money Magic"}],"role":"collection"},"doc://com.moneykit.link/documentation/MoneyKit/MKConnectViewModel/linkHandler":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"linkHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@MoneyKit@objc(cs)MKLinkHandler","text":"MKLinkHandler"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKConnectViewModel\/linkHandler","url":"\/documentation\/moneykit\/mkconnectviewmodel\/linkhandler","role":"symbol","kind":"symbol","abstract":[],"title":"linkHandler"},"doc://com.moneykit.link/documentation/MoneyKit/MKConnectViewModel":{"abstract":[],"title":"MKConnectViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MKConnectViewModel","kind":"identifier"}],"url":"\/documentation\/moneykit\/mkconnectviewmodel","identifier":"doc:\/\/com.moneykit.link\/documentation\/MoneyKit\/MKConnectViewModel","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MKConnectViewModel"}]}},"variantOverrides":[{"patch":[{"value":"MKLinkHandler","op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/fragments","value":[{"kind":"identifier","text":"MKLinkHandler"}]},{"op":"replace","path":"\/references\/doc:~1~1com.moneykit.link~1documentation~1MoneyKit~1MKLinkHandler\/navigatorTitle","value":[{"text":"MKLinkHandler","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}